// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type ChangeReasonStatusRequest struct {
	// change the status of a closing reason
	ChangeReasonStatusReq *shared.ChangeReasonStatusReq `request:"mediaType=application/json"`
	ReasonID              string                        `pathParam:"style=simple,explode=false,name=reasonId"`
}

func (c *ChangeReasonStatusRequest) GetChangeReasonStatusReq() *shared.ChangeReasonStatusReq {
	if c == nil {
		return nil
	}
	return c.ChangeReasonStatusReq
}

func (c *ChangeReasonStatusRequest) GetReasonID() string {
	if c == nil {
		return ""
	}
	return c.ReasonID
}

type ChangeReasonStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// bad request
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *ChangeReasonStatusResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ChangeReasonStatusResponse) GetErrorResp() *shared.ErrorResp {
	if c == nil {
		return nil
	}
	return c.ErrorResp
}

func (c *ChangeReasonStatusResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ChangeReasonStatusResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
