// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type DeleteFlowTemplateRequest struct {
	// Id of the flow template to de deleted.
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
}

func (o *DeleteFlowTemplateRequest) GetFlowID() string {
	if o == nil {
		return ""
	}
	return o.FlowID
}

type DeleteFlowTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Failed to authenticate
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteFlowTemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteFlowTemplateResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *DeleteFlowTemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteFlowTemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
