// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type DeleteClosingReasonRequest struct {
	// unique id to identify the closing reason.
	ReasonID string `pathParam:"style=simple,explode=false,name=reasonId"`
}

func (d *DeleteClosingReasonRequest) GetReasonID() string {
	if d == nil {
		return ""
	}
	return d.ReasonID
}

type DeleteClosingReasonResponse struct {
	// Closing reason not found
	ClosingReasonNotFoundResp *shared.ClosingReasonNotFoundResp
	// HTTP response content type for this operation
	ContentType string
	// Forbidden
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteClosingReasonResponse) GetClosingReasonNotFoundResp() *shared.ClosingReasonNotFoundResp {
	if d == nil {
		return nil
	}
	return d.ClosingReasonNotFoundResp
}

func (d *DeleteClosingReasonResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteClosingReasonResponse) GetErrorResp() *shared.ErrorResp {
	if d == nil {
		return nil
	}
	return d.ErrorResp
}

func (d *DeleteClosingReasonResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteClosingReasonResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
