// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type DuplicateFlowTemplateRequest struct {
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
}

func (o *DuplicateFlowTemplateRequest) GetFlowID() string {
	if o == nil {
		return ""
	}
	return o.FlowID
}

type DuplicateFlowTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// Flow template has been duplicated successfully
	FlowTemplate *shared.FlowTemplate
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DuplicateFlowTemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DuplicateFlowTemplateResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *DuplicateFlowTemplateResponse) GetFlowTemplate() *shared.FlowTemplate {
	if o == nil {
		return nil
	}
	return o.FlowTemplate
}

func (o *DuplicateFlowTemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DuplicateFlowTemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
