// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type GetClosingReasonV1Request struct {
	// uuid to identify the closing reason.
	ReasonID string `pathParam:"style=simple,explode=false,name=reasonId"`
}

func (g *GetClosingReasonV1Request) GetReasonID() string {
	if g == nil {
		return ""
	}
	return g.ReasonID
}

type GetClosingReasonV1Response struct {
	// Returns the closing reason
	ClosingReason *shared.ClosingReason
	// Closing reason not found
	ClosingReasonNotFoundResp *shared.ClosingReasonNotFoundResp
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetClosingReasonV1Response) GetClosingReason() *shared.ClosingReason {
	if g == nil {
		return nil
	}
	return g.ClosingReason
}

func (g *GetClosingReasonV1Response) GetClosingReasonNotFoundResp() *shared.ClosingReasonNotFoundResp {
	if g == nil {
		return nil
	}
	return g.ClosingReasonNotFoundResp
}

func (g *GetClosingReasonV1Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetClosingReasonV1Response) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetClosingReasonV1Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetClosingReasonV1Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
