// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type GetClosingReasonRequest struct {
	// uuid to identify the closing reason.
	ReasonID string `pathParam:"style=simple,explode=false,name=reasonId"`
}

func (o *GetClosingReasonRequest) GetReasonID() string {
	if o == nil {
		return ""
	}
	return o.ReasonID
}

type GetClosingReasonResponse struct {
	// Returns the closing reason
	ClosingReason *shared.ClosingReason
	// Closing reason not found
	ClosingReasonNotFoundResp *shared.ClosingReasonNotFoundResp
	// HTTP response content type for this operation
	ContentType string
	// Validation Errors
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetClosingReasonResponse) GetClosingReason() *shared.ClosingReason {
	if o == nil {
		return nil
	}
	return o.ClosingReason
}

func (o *GetClosingReasonResponse) GetClosingReasonNotFoundResp() *shared.ClosingReasonNotFoundResp {
	if o == nil {
		return nil
	}
	return o.ClosingReasonNotFoundResp
}

func (o *GetClosingReasonResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetClosingReasonResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetClosingReasonResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetClosingReasonResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
