// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type GetMaxAllowedLimitResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Other errors
	ErrorResp *shared.ErrorResp
	// A combo of current number of workflows, and the max allowed number of workflows.
	MaxAllowedLimit *shared.MaxAllowedLimit
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetMaxAllowedLimitResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMaxAllowedLimitResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetMaxAllowedLimitResponse) GetMaxAllowedLimit() *shared.MaxAllowedLimit {
	if g == nil {
		return nil
	}
	return g.MaxAllowedLimit
}

func (g *GetMaxAllowedLimitResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMaxAllowedLimitResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
