// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/models/shared"
	"net/http"
)

type GetWorkflowClosingReasonsRequest struct {
	// ID of a workflow definition
	DefinitionID string `pathParam:"style=simple,explode=false,name=definitionId"`
}

func (g *GetWorkflowClosingReasonsRequest) GetDefinitionID() string {
	if g == nil {
		return ""
	}
	return g.DefinitionID
}

type GetWorkflowClosingReasonsResponse struct {
	// Returns the entire catalog of closing reasons for a specific workflow
	ClosingReasonsIds *shared.ClosingReasonsIds
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetWorkflowClosingReasonsResponse) GetClosingReasonsIds() *shared.ClosingReasonsIds {
	if g == nil {
		return nil
	}
	return g.ClosingReasonsIds
}

func (g *GetWorkflowClosingReasonsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetWorkflowClosingReasonsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetWorkflowClosingReasonsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
