// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BaseRelationDollarRelation struct {
	Tags     []string `json:"_tags,omitempty"`
	EntityID *string  `json:"entity_id,omitempty"`
}

func (o *BaseRelationDollarRelation) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *BaseRelationDollarRelation) GetEntityID() *string {
	if o == nil {
		return nil
	}
	return o.EntityID
}

type BaseRelation struct {
	DollarRelation []BaseRelationDollarRelation `json:"$relation,omitempty"`
}

func (o *BaseRelation) GetDollarRelation() []BaseRelationDollarRelation {
	if o == nil {
		return nil
	}
	return o.DollarRelation
}
