// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EntityOwner - The user / organization owning this entity.
//
// Note: Owner implicitly has access to the entity regardless of ACLs.
type EntityOwner struct {
	OrgID  string  `json:"org_id"`
	UserID *string `json:"user_id,omitempty"`
}

func (o *EntityOwner) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *EntityOwner) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}
