// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/pkg/utils"
)

// ProductPatchCrossSellableProducts - Stores references to products that can be cross sold with the current product.
type ProductPatchCrossSellableProducts struct {
	DollarRelation []BaseRelation `json:"$relation,omitempty"`
}

func (o *ProductPatchCrossSellableProducts) GetDollarRelation() []BaseRelation {
	if o == nil {
		return nil
	}
	return o.DollarRelation
}

type ProductPatchFeature struct {
	// An arbitrary set of tags attached to a feature
	Tags    []string `json:"_tags,omitempty"`
	Feature *string  `json:"feature,omitempty"`
}

func (o *ProductPatchFeature) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *ProductPatchFeature) GetFeature() *string {
	if o == nil {
		return nil
	}
	return o.Feature
}

// ProductPatchProductDownloads - Stores references to a set of files downloadable from the product.
// e.g: tech specifications, quality control sheets, privacy policy agreements
type ProductPatchProductDownloads struct {
	DollarRelation []BaseRelation `json:"$relation,omitempty"`
}

func (o *ProductPatchProductDownloads) GetDollarRelation() []BaseRelation {
	if o == nil {
		return nil
	}
	return o.DollarRelation
}

// ProductPatchProductImages - Stores references to a set of file images of the product
type ProductPatchProductImages struct {
	DollarRelation []BaseRelation `json:"$relation,omitempty"`
}

func (o *ProductPatchProductImages) GetDollarRelation() []BaseRelation {
	if o == nil {
		return nil
	}
	return o.DollarRelation
}

// ProductPatchType - The type of Product:
//
// | type | description |
// |----| ----|
// | `product` | Represents a physical good |
// | `service` | Represents a service or virtual product |
type ProductPatchType string

const (
	ProductPatchTypeProduct ProductPatchType = "product"
	ProductPatchTypeService ProductPatchType = "service"
)

func (e ProductPatchType) ToPointer() *ProductPatchType {
	return &e
}

func (e *ProductPatchType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "product":
		fallthrough
	case "service":
		*e = ProductPatchType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductPatchType: %v", v)
	}
}

type ProductPatch struct {
	// Stores references to the availability files that define where this product is available.
	// These files are used when interacting with products via epilot Journeys, thought the AvailabilityCheck block.
	//
	AvailabilityFiles []BaseRelation `json:"availability_files,omitempty"`
	// The product code
	Code *string `json:"code,omitempty"`
	// Stores references to products that can be cross sold with the current product.
	CrossSellableProducts *ProductPatchCrossSellableProducts `json:"cross_sellable_products,omitempty"`
	// A description of the product. Multi-line supported.
	Description *string               `json:"description,omitempty"`
	Feature     []ProductPatchFeature `json:"feature,omitempty"`
	// Not visible to customers, only in internal tables
	InternalName *string `json:"internal_name,omitempty"`
	// The description for the product
	Name         *string       `json:"name,omitempty"`
	PriceOptions *BaseRelation `json:"price_options,omitempty"`
	// Stores references to a set of files downloadable from the product.
	// e.g: tech specifications, quality control sheets, privacy policy agreements
	//
	ProductDownloads *ProductPatchProductDownloads `json:"product_downloads,omitempty"`
	// Stores references to a set of file images of the product
	ProductImages *ProductPatchProductImages `json:"product_images,omitempty"`
	// The type of Product:
	//
	// | type | description |
	// |----| ----|
	// | `product` | Represents a physical good |
	// | `service` | Represents a service or virtual product |
	//
	Type *ProductPatchType `default:"product" json:"type"`
}

func (p ProductPatch) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductPatch) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ProductPatch) GetAvailabilityFiles() []BaseRelation {
	if o == nil {
		return nil
	}
	return o.AvailabilityFiles
}

func (o *ProductPatch) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ProductPatch) GetCrossSellableProducts() *ProductPatchCrossSellableProducts {
	if o == nil {
		return nil
	}
	return o.CrossSellableProducts
}

func (o *ProductPatch) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ProductPatch) GetFeature() []ProductPatchFeature {
	if o == nil {
		return nil
	}
	return o.Feature
}

func (o *ProductPatch) GetInternalName() *string {
	if o == nil {
		return nil
	}
	return o.InternalName
}

func (o *ProductPatch) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ProductPatch) GetPriceOptions() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.PriceOptions
}

func (o *ProductPatch) GetProductDownloads() *ProductPatchProductDownloads {
	if o == nil {
		return nil
	}
	return o.ProductDownloads
}

func (o *ProductPatch) GetProductImages() *ProductPatchProductImages {
	if o == nil {
		return nil
	}
	return o.ProductImages
}

func (o *ProductPatch) GetType() *ProductPatchType {
	if o == nil {
		return nil
	}
	return o.Type
}
