// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/pkg/utils"
)

type ProductPatchFeature struct {
	ID      *string  `json:"_id,omitempty"`
	Tags    []string `json:"_tags,omitempty"`
	Feature *string  `json:"feature,omitempty"`
}

func (o *ProductPatchFeature) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ProductPatchFeature) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *ProductPatchFeature) GetFeature() *string {
	if o == nil {
		return nil
	}
	return o.Feature
}

// ProductPatchType - The type of Product:
//
// | type | description |
// |----| ----|
// | `product` | Represents a physical good |
// | `service` | Represents a service or virtual product |
type ProductPatchType string

const (
	ProductPatchTypeProduct ProductPatchType = "product"
	ProductPatchTypeService ProductPatchType = "service"
)

func (e ProductPatchType) ToPointer() *ProductPatchType {
	return &e
}

func (e *ProductPatchType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "product":
		fallthrough
	case "service":
		*e = ProductPatchType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductPatchType: %v", v)
	}
}

type ProductPatch struct {
	Active *bool `json:"active,omitempty"`
	// The product code
	Code *string `json:"code,omitempty"`
	// A description of the product. Multi-line supported.
	Description *string               `json:"description,omitempty"`
	Feature     []ProductPatchFeature `json:"feature,omitempty"`
	// Not visible to customers, only in internal tables
	InternalName *string `json:"internal_name,omitempty"`
	// The description for the product
	Name         *string       `json:"name,omitempty"`
	PriceOptions *BaseRelation `json:"price_options,omitempty"`
	// The type of Product:
	//
	// | type | description |
	// |----| ----|
	// | `product` | Represents a physical good |
	// | `service` | Represents a service or virtual product |
	//
	Type *ProductPatchType `default:"product" json:"type"`
}

func (p ProductPatch) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductPatch) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ProductPatch) GetActive() *bool {
	if o == nil {
		return nil
	}
	return o.Active
}

func (o *ProductPatch) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ProductPatch) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ProductPatch) GetFeature() []ProductPatchFeature {
	if o == nil {
		return nil
	}
	return o.Feature
}

func (o *ProductPatch) GetInternalName() *string {
	if o == nil {
		return nil
	}
	return o.InternalName
}

func (o *ProductPatch) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ProductPatch) GetPriceOptions() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.PriceOptions
}

func (o *ProductPatch) GetType() *ProductPatchType {
	if o == nil {
		return nil
	}
	return o.Type
}
