// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

// ActionConfig - Transient field. The full automation action configuration following the automation API action schema. Processed by the backend during create/update and stripped before storage. When present without a flow_id, a new automation flow is created. When present with a flow_id, the existing automation flow is updated.
type ActionConfig struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Action-specific configuration
	Config map[string]any `json:"config,omitempty"`
	// The action type (e.g. send-email, trigger-workflow)
	Type string `json:"type"`
}

func (a ActionConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActionConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ActionConfig) GetAdditionalProperties() any {
	if a == nil {
		return nil
	}
	return a.AdditionalProperties
}

func (a *ActionConfig) GetConfig() map[string]any {
	if a == nil {
		return nil
	}
	return a.Config
}

func (a *ActionConfig) GetType() string {
	if a == nil {
		return ""
	}
	return a.Type
}

// AutomationConfig - Configuration for automation execution to run
type AutomationConfig struct {
	// Transient field. The full automation action configuration following the automation API action schema. Processed by the backend during create/update and stripped before storage. When present without a flow_id, a new automation flow is created. When present with a flow_id, the existing automation flow is updated.
	//
	ActionConfig *ActionConfig `json:"action_config,omitempty"`
	// Transient field. When present, the backend clones the automation flow referenced by this ID and assigns the new flow_id to the task. Used when duplicating an automation task to give it an independent automation. Stripped before storage.
	//
	DuplicatedFlowID *string `json:"duplicated_flow_id,omitempty"`
	// Id of the configured automation to run
	FlowID *string `json:"flow_id,omitempty"`
	// Optional. Source of the entity fed into this automation task. If omitted, the workflow's primary entity is used.
	//
	InputContext *AutomationInputContext `json:"input_context,omitempty"`
}

func (a AutomationConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationConfig) GetActionConfig() *ActionConfig {
	if a == nil {
		return nil
	}
	return a.ActionConfig
}

func (a *AutomationConfig) GetDuplicatedFlowID() *string {
	if a == nil {
		return nil
	}
	return a.DuplicatedFlowID
}

func (a *AutomationConfig) GetFlowID() *string {
	if a == nil {
		return nil
	}
	return a.FlowID
}

func (a *AutomationConfig) GetInputContext() *AutomationInputContext {
	if a == nil {
		return nil
	}
	return a.InputContext
}
