// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

// Source - `trigger` = workflow's primary (trigger) entity. `task` = entity produced by an upstream task in the graph.
type Source string

const (
	SourceTrigger Source = "trigger"
	SourceTask    Source = "task"
)

func (e Source) ToPointer() *Source {
	return &e
}
func (e *Source) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "trigger":
		fallthrough
	case "task":
		*e = Source(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Source: %v", v)
	}
}

// AutomationInputContext - Optional. Source of the entity fed into this automation task. If omitted, the workflow's primary entity is used.
type AutomationInputContext struct {
	// `trigger` = workflow's primary (trigger) entity. `task` = entity produced by an upstream task in the graph.
	//
	Source Source `json:"source"`
	// Required when source is `task`. The id of the upstream task whose output entity should feed this task.
	TaskID *string `json:"task_id,omitempty"`
}

func (a AutomationInputContext) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AutomationInputContext) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AutomationInputContext) GetSource() Source {
	if a == nil {
		return Source("")
	}
	return a.Source
}

func (a *AutomationInputContext) GetTaskID() *string {
	if a == nil {
		return nil
	}
	return a.TaskID
}
