// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ClosingReasons struct {
	Reasons []ClosingReason `json:"reasons"`
}

func (c *ClosingReasons) GetReasons() []ClosingReason {
	if c == nil {
		return []ClosingReason{}
	}
	return c.Reasons
}
