// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ClosingReasonInput - One Closing reason for a workflow
type ClosingReasonInput struct {
	Status ClosingReasonsStatus `json:"status"`
	Title  string               `json:"title"`
}

func (c *ClosingReasonInput) GetStatus() ClosingReasonsStatus {
	if c == nil {
		return ClosingReasonsStatus("")
	}
	return c.Status
}

func (c *ClosingReasonInput) GetTitle() string {
	if c == nil {
		return ""
	}
	return c.Title
}
