// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ClosingReasonsIds struct {
	Reasons []ClosingReasonID `json:"reasons"`
}

func (c *ClosingReasonsIds) GetReasons() []ClosingReasonID {
	if c == nil {
		return []ClosingReasonID{}
	}
	return c.Reasons
}
