// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ClosingReasonsIds struct {
	Reasons []ClosingReasonID `json:"reasons"`
}

func (o *ClosingReasonsIds) GetReasons() []ClosingReasonID {
	if o == nil {
		return []ClosingReasonID{}
	}
	return o.Reasons
}
