// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

type CreateFlowTemplateClosingReasons struct {
	ID string `json:"id"`
}

func (o *CreateFlowTemplateClosingReasons) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CreateFlowTemplate struct {
	AssignedTo []string `json:"assigned_to,omitempty"`
	// Indicates whether this workflow is available for End Customer Portal or not. By default it's not.
	AvailableInEcp *bool                              `json:"available_in_ecp,omitempty"`
	ClosingReasons []CreateFlowTemplateClosingReasons `json:"closing_reasons,omitempty"`
	// ISO String Date & Time
	CreatedAt   *string `json:"created_at,omitempty"`
	Description *string `json:"description,omitempty"`
	DueDate     *string `json:"due_date,omitempty"`
	// Set due date for the task based on a dynamic condition
	DueDateConfig *DueDateConfig `json:"due_date_config,omitempty"`
	Edges         []Edge         `json:"edges"`
	// Whether the workflow is enabled or not
	Enabled    *bool        `default:"true" json:"enabled"`
	EntitySync []EntitySync `json:"entity_sync,omitempty"`
	ID         *string      `json:"id,omitempty"`
	Name       string       `json:"name"`
	OrgID      *string      `json:"org_id,omitempty"`
	Phases     []Phase      `json:"phases,omitempty"`
	// Whether only a single closing reason can be selected
	SingleClosingReasonSelection *bool  `json:"singleClosingReasonSelection,omitempty"`
	Tasks                        []Task `json:"tasks"`
	// Taxonomy ids that are associated with this workflow and used for filtering
	Taxonomies []string `json:"taxonomies,omitempty"`
	Trigger    *Trigger `json:"trigger,omitempty"`
	// ISO String Date & Time
	UpdatedAt *string `json:"updated_at,omitempty"`
	// Version of the workflow schema.
	//
	// - `v1` – *Deprecated*. The initial version of workflows with limited structure and automation capabilities.
	// - `v2` – Linear workflows. Supports sequential task execution with basic automation triggers.
	// - `v3` – Advanced workflows. Adds support for branching logic (conditions), parallel paths, and enhanced automation features such as dynamic triggers and flow control.
	//
	Version *Version `json:"version,omitempty"`
}

func (c CreateFlowTemplate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFlowTemplate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"edges", "name", "tasks"}); err != nil {
		return err
	}
	return nil
}

func (o *CreateFlowTemplate) GetAssignedTo() []string {
	if o == nil {
		return nil
	}
	return o.AssignedTo
}

func (o *CreateFlowTemplate) GetAvailableInEcp() *bool {
	if o == nil {
		return nil
	}
	return o.AvailableInEcp
}

func (o *CreateFlowTemplate) GetClosingReasons() []CreateFlowTemplateClosingReasons {
	if o == nil {
		return nil
	}
	return o.ClosingReasons
}

func (o *CreateFlowTemplate) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *CreateFlowTemplate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateFlowTemplate) GetDueDate() *string {
	if o == nil {
		return nil
	}
	return o.DueDate
}

func (o *CreateFlowTemplate) GetDueDateConfig() *DueDateConfig {
	if o == nil {
		return nil
	}
	return o.DueDateConfig
}

func (o *CreateFlowTemplate) GetEdges() []Edge {
	if o == nil {
		return []Edge{}
	}
	return o.Edges
}

func (o *CreateFlowTemplate) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *CreateFlowTemplate) GetEntitySync() []EntitySync {
	if o == nil {
		return nil
	}
	return o.EntitySync
}

func (o *CreateFlowTemplate) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateFlowTemplate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateFlowTemplate) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *CreateFlowTemplate) GetPhases() []Phase {
	if o == nil {
		return nil
	}
	return o.Phases
}

func (o *CreateFlowTemplate) GetSingleClosingReasonSelection() *bool {
	if o == nil {
		return nil
	}
	return o.SingleClosingReasonSelection
}

func (o *CreateFlowTemplate) GetTasks() []Task {
	if o == nil {
		return []Task{}
	}
	return o.Tasks
}

func (o *CreateFlowTemplate) GetTaxonomies() []string {
	if o == nil {
		return nil
	}
	return o.Taxonomies
}

func (o *CreateFlowTemplate) GetTrigger() *Trigger {
	if o == nil {
		return nil
	}
	return o.Trigger
}

func (o *CreateFlowTemplate) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *CreateFlowTemplate) GetVersion() *Version {
	if o == nil {
		return nil
	}
	return o.Version
}
