// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// DefinitionNotFoundResp - Definition could be not found
type DefinitionNotFoundResp struct {
	Message *string `json:"message,omitempty"`
}

func (d *DefinitionNotFoundResp) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}
