// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

// ECPDetails - Details regarding ECP for the workflow step
type ECPDetails struct {
	Description *string      `json:"description,omitempty"`
	Enabled     *bool        `json:"enabled,omitempty"`
	Journey     *StepJourney `json:"journey,omitempty"`
	Label       *string      `json:"label,omitempty"`
}

func (o *ECPDetails) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ECPDetails) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *ECPDetails) GetJourney() *StepJourney {
	if o == nil {
		return nil
	}
	return o.Journey
}

func (o *ECPDetails) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}
