// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Edge struct {
	ConditionID *string `json:"condition_id,omitempty"`
	FromID      string  `json:"from_id"`
	ID          string  `json:"id"`
	ToID        string  `json:"to_id"`
}

func (o *Edge) GetConditionID() *string {
	if o == nil {
		return nil
	}
	return o.ConditionID
}

func (o *Edge) GetFromID() string {
	if o == nil {
		return ""
	}
	return o.FromID
}

func (o *Edge) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Edge) GetToID() string {
	if o == nil {
		return ""
	}
	return o.ToID
}
