// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Edge struct {
	ConditionID *string `json:"condition_id,omitempty"`
	FromID      string  `json:"from_id"`
	ID          string  `json:"id"`
	// Indicates a default case for a decision task. Only decision task edges can have this field and the flow advances using this edge if no conditions are met.
	NoneMet *bool  `json:"none_met,omitempty"`
	ToID    string `json:"to_id"`
}

func (o *Edge) GetConditionID() *string {
	if o == nil {
		return nil
	}
	return o.ConditionID
}

func (o *Edge) GetFromID() string {
	if o == nil {
		return ""
	}
	return o.FromID
}

func (o *Edge) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Edge) GetNoneMet() *bool {
	if o == nil {
		return nil
	}
	return o.NoneMet
}

func (o *Edge) GetToID() string {
	if o == nil {
		return ""
	}
	return o.ToID
}
