// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Target struct {
	EntityAttribute string `json:"entityAttribute"`
	EntitySchema    string `json:"entitySchema"`
}

func (t *Target) GetEntityAttribute() string {
	if t == nil {
		return ""
	}
	return t.EntityAttribute
}

func (t *Target) GetEntitySchema() string {
	if t == nil {
		return ""
	}
	return t.EntitySchema
}

// Event or condition that triggers the entity sync.
// Direct triggers match EventBridge event names (PascalCase).
// Status triggers are deduced from event + entity status combination.
type Event string

const (
	EventFlowStarted           Event = "FlowStarted"
	EventFlowCompleted         Event = "FlowCompleted"
	EventFlowCancelled         Event = "FlowCancelled"
	EventFlowReopened          Event = "FlowReopened"
	EventFlowDeleted           Event = "FlowDeleted"
	EventFlowAssigned          Event = "FlowAssigned"
	EventFlowDueDateChanged    Event = "FlowDueDateChanged"
	EventFlowContextsChanged   Event = "FlowContextsChanged"
	EventTaskUpdated           Event = "TaskUpdated"
	EventCurrTaskChanged       Event = "CurrTaskChanged"
	EventTaskCompleted         Event = "TaskCompleted"
	EventTaskSkipped           Event = "TaskSkipped"
	EventTaskMarkedInProgress  Event = "TaskMarkedInProgress"
	EventPhaseUpdated          Event = "PhaseUpdated"
	EventPhaseCompleted        Event = "PhaseCompleted"
	EventPhaseSkipped          Event = "PhaseSkipped"
	EventPhaseMarkedInProgress Event = "PhaseMarkedInProgress"
)

func (e Event) ToPointer() *Event {
	return &e
}
func (e *Event) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FlowStarted":
		fallthrough
	case "FlowCompleted":
		fallthrough
	case "FlowCancelled":
		fallthrough
	case "FlowReopened":
		fallthrough
	case "FlowDeleted":
		fallthrough
	case "FlowAssigned":
		fallthrough
	case "FlowDueDateChanged":
		fallthrough
	case "FlowContextsChanged":
		fallthrough
	case "TaskUpdated":
		fallthrough
	case "CurrTaskChanged":
		fallthrough
	case "TaskCompleted":
		fallthrough
	case "TaskSkipped":
		fallthrough
	case "TaskMarkedInProgress":
		fallthrough
	case "PhaseUpdated":
		fallthrough
	case "PhaseCompleted":
		fallthrough
	case "PhaseSkipped":
		fallthrough
	case "PhaseMarkedInProgress":
		*e = Event(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Event: %v", v)
	}
}

// Filter - Optional filter to target specific tasks or phases.
// Specify either task_template_id OR phase_template_id (mutually exclusive).
// If omitted, trigger applies to all tasks/phases.
type Filter struct {
	// Target a specific phase by its template ID (stable across executions)
	PhaseTemplateID *string `json:"phase_template_id,omitempty"`
	// Target a specific task by its template ID (stable across executions)
	TaskTemplateID *string `json:"task_template_id,omitempty"`
}

func (f *Filter) GetPhaseTemplateID() *string {
	if f == nil {
		return nil
	}
	return f.PhaseTemplateID
}

func (f *Filter) GetTaskTemplateID() *string {
	if f == nil {
		return nil
	}
	return f.TaskTemplateID
}

// EntitySyncTrigger - Trigger configuration that determines when entity sync occurs.
// Contains the event type and optional filter to target specific tasks/phases.
type EntitySyncTrigger struct {
	// Event or condition that triggers the entity sync.
	// Direct triggers match EventBridge event names (PascalCase).
	// Status triggers are deduced from event + entity status combination.
	//
	Event Event `json:"event"`
	// Optional filter to target specific tasks or phases.
	// Specify either task_template_id OR phase_template_id (mutually exclusive).
	// If omitted, trigger applies to all tasks/phases.
	//
	Filter *Filter `json:"filter,omitempty"`
}

func (e *EntitySyncTrigger) GetEvent() Event {
	if e == nil {
		return Event("")
	}
	return e.Event
}

func (e *EntitySyncTrigger) GetFilter() *Filter {
	if e == nil {
		return nil
	}
	return e.Filter
}

type EntitySyncSource string

const (
	EntitySyncSourceWorkflowName       EntitySyncSource = "workflow_name"
	EntitySyncSourceWorkflowStatus     EntitySyncSource = "workflow_status"
	EntitySyncSourceWorkflowAssignedTo EntitySyncSource = "workflow_assigned_to"
	EntitySyncSourceTaskName           EntitySyncSource = "task_name"
	EntitySyncSourceTaskStatus         EntitySyncSource = "task_status"
	EntitySyncSourceTaskAssignedTo     EntitySyncSource = "task_assigned_to"
	EntitySyncSourcePhaseName          EntitySyncSource = "phase_name"
	EntitySyncSourcePhaseStatus        EntitySyncSource = "phase_status"
	EntitySyncSourcePhaseAssignedTo    EntitySyncSource = "phase_assigned_to"
	EntitySyncSourceCustomValue        EntitySyncSource = "custom_value"
)

func (e EntitySyncSource) ToPointer() *EntitySyncSource {
	return &e
}
func (e *EntitySyncSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "workflow_name":
		fallthrough
	case "workflow_status":
		fallthrough
	case "workflow_assigned_to":
		fallthrough
	case "task_name":
		fallthrough
	case "task_status":
		fallthrough
	case "task_assigned_to":
		fallthrough
	case "phase_name":
		fallthrough
	case "phase_status":
		fallthrough
	case "phase_assigned_to":
		fallthrough
	case "custom_value":
		*e = EntitySyncSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntitySyncSource: %v", v)
	}
}

type Value struct {
	Source EntitySyncSource `json:"source"`
	Value  *string          `json:"value,omitempty"`
}

func (v *Value) GetSource() EntitySyncSource {
	if v == nil {
		return EntitySyncSource("")
	}
	return v.Source
}

func (v *Value) GetValue() *string {
	if v == nil {
		return nil
	}
	return v.Value
}

type EntitySync struct {
	Target Target `json:"target"`
	// Trigger configuration that determines when entity sync occurs.
	// Contains the event type and optional filter to target specific tasks/phases.
	//
	Trigger EntitySyncTrigger `json:"trigger"`
	Value   Value             `json:"value"`
}

func (e *EntitySync) GetTarget() Target {
	if e == nil {
		return Target{}
	}
	return e.Target
}

func (e *EntitySync) GetTrigger() EntitySyncTrigger {
	if e == nil {
		return EntitySyncTrigger{}
	}
	return e.Trigger
}

func (e *EntitySync) GetValue() Value {
	if e == nil {
		return Value{}
	}
	return e.Value
}
