// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

type JourneyAutomationTriggerType string

const (
	JourneyAutomationTriggerTypeJourneyAutomation JourneyAutomationTriggerType = "journey_automation"
)

func (e JourneyAutomationTriggerType) ToPointer() *JourneyAutomationTriggerType {
	return &e
}
func (e *JourneyAutomationTriggerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey_automation":
		*e = JourneyAutomationTriggerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneyAutomationTriggerType: %v", v)
	}
}

type JourneyAutomationTrigger struct {
	// Schema of the main entity where flow will be triggered. The entity will be picked from automation context.
	EntitySchema *string                      `json:"entity_schema,omitempty"`
	ID           *string                      `json:"id,omitempty"`
	Type         JourneyAutomationTriggerType `json:"type"`
}

func (j JourneyAutomationTrigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JourneyAutomationTrigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *JourneyAutomationTrigger) GetEntitySchema() *string {
	if o == nil {
		return nil
	}
	return o.EntitySchema
}

func (o *JourneyAutomationTrigger) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *JourneyAutomationTrigger) GetType() JourneyAutomationTriggerType {
	if o == nil {
		return JourneyAutomationTriggerType("")
	}
	return o.Type
}
