// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

type JourneySubmissionTriggerType string

const (
	JourneySubmissionTriggerTypeJourneySubmission JourneySubmissionTriggerType = "journey_submission"
)

func (e JourneySubmissionTriggerType) ToPointer() *JourneySubmissionTriggerType {
	return &e
}
func (e *JourneySubmissionTriggerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "journey_submission":
		*e = JourneySubmissionTriggerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JourneySubmissionTriggerType: %v", v)
	}
}

type JourneySubmissionTrigger struct {
	AutomationID *string `json:"automation_id,omitempty"`
	ID           *string `json:"id,omitempty"`
	// ID of the journey that will trigger this flow
	JourneyID string `json:"journey_id"`
	// Name of the journey that will trigger this flow
	JourneyName *string                      `json:"journey_name,omitempty"`
	Type        JourneySubmissionTriggerType `json:"type"`
}

func (j JourneySubmissionTrigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JourneySubmissionTrigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, []string{"journey_id", "type"}); err != nil {
		return err
	}
	return nil
}

func (j *JourneySubmissionTrigger) GetAutomationID() *string {
	if j == nil {
		return nil
	}
	return j.AutomationID
}

func (j *JourneySubmissionTrigger) GetID() *string {
	if j == nil {
		return nil
	}
	return j.ID
}

func (j *JourneySubmissionTrigger) GetJourneyID() string {
	if j == nil {
		return ""
	}
	return j.JourneyID
}

func (j *JourneySubmissionTrigger) GetJourneyName() *string {
	if j == nil {
		return nil
	}
	return j.JourneyName
}

func (j *JourneySubmissionTrigger) GetType() JourneySubmissionTriggerType {
	if j == nil {
		return JourneySubmissionTriggerType("")
	}
	return j.Type
}
