// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

type ManualTriggerType string

const (
	ManualTriggerTypeManual ManualTriggerType = "manual"
)

func (e ManualTriggerType) ToPointer() *ManualTriggerType {
	return &e
}
func (e *ManualTriggerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual":
		*e = ManualTriggerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ManualTriggerType: %v", v)
	}
}

type ManualTrigger struct {
	EntitySchema *string           `json:"entity_schema,omitempty"`
	ID           *string           `json:"id,omitempty"`
	Type         ManualTriggerType `json:"type"`
}

func (m ManualTrigger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *ManualTrigger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (m *ManualTrigger) GetEntitySchema() *string {
	if m == nil {
		return nil
	}
	return m.EntitySchema
}

func (m *ManualTrigger) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *ManualTrigger) GetType() ManualTriggerType {
	if m == nil {
		return ManualTriggerType("")
	}
	return m.Type
}
