// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

// Section - A group of Steps that define the progress of the Workflow
type Section struct {
	ID    *string  `json:"id,omitempty"`
	Name  string   `json:"name"`
	Order float64  `json:"order"`
	Steps []Step   `json:"steps"`
	Type  ItemType `json:"type"`
}

func (s Section) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Section) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"name", "order", "steps", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *Section) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *Section) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Section) GetOrder() float64 {
	if s == nil {
		return 0.0
	}
	return s.Order
}

func (s *Section) GetSteps() []Step {
	if s == nil {
		return []Step{}
	}
	return s.Steps
}

func (s *Section) GetType() ItemType {
	if s == nil {
		return ItemType("")
	}
	return s.Type
}
