// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Statement struct {
	ID       string           `json:"id"`
	Operator Operator         `json:"operator"`
	Source   EvaluationSource `json:"source"`
	Values   []string         `json:"values"`
}

func (o *Statement) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Statement) GetOperator() Operator {
	if o == nil {
		return Operator("")
	}
	return o.Operator
}

func (o *Statement) GetSource() EvaluationSource {
	if o == nil {
		return EvaluationSource{}
	}
	return o.Source
}

func (o *Statement) GetValues() []string {
	if o == nil {
		return []string{}
	}
	return o.Values
}
