// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

type StepRequirementCondition string

const (
	StepRequirementConditionClosed StepRequirementCondition = "CLOSED"
)

func (e StepRequirementCondition) ToPointer() *StepRequirementCondition {
	return &e
}
func (e *StepRequirementCondition) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CLOSED":
		*e = StepRequirementCondition(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StepRequirementCondition: %v", v)
	}
}

// StepRequirement - describe the requirement for step enablement
type StepRequirement struct {
	Condition    StepRequirementCondition `json:"condition"`
	DefinitionID string                   `json:"definitionId"`
	Type         ItemType                 `json:"type"`
}

func (s StepRequirement) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StepRequirement) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"condition", "definitionId", "type"}); err != nil {
		return err
	}
	return nil
}

func (o *StepRequirement) GetCondition() StepRequirementCondition {
	if o == nil {
		return StepRequirementCondition("")
	}
	return o.Condition
}

func (o *StepRequirement) GetDefinitionID() string {
	if o == nil {
		return ""
	}
	return o.DefinitionID
}

func (o *StepRequirement) GetType() ItemType {
	if o == nil {
		return ItemType("")
	}
	return o.Type
}
