// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

type TriggerUnionType string

const (
	TriggerUnionTypeManualTrigger            TriggerUnionType = "ManualTrigger"
	TriggerUnionTypeAutomationTrigger        TriggerUnionType = "AutomationTrigger"
	TriggerUnionTypeJourneySubmissionTrigger TriggerUnionType = "JourneySubmissionTrigger"
	TriggerUnionTypeJourneyAutomationTrigger TriggerUnionType = "JourneyAutomationTrigger"
)

type Trigger struct {
	ManualTrigger            *ManualTrigger            `queryParam:"inline"`
	AutomationTrigger        *AutomationTrigger        `queryParam:"inline"`
	JourneySubmissionTrigger *JourneySubmissionTrigger `queryParam:"inline"`
	JourneyAutomationTrigger *JourneyAutomationTrigger `queryParam:"inline"`

	Type TriggerUnionType
}

func CreateTriggerManualTrigger(manualTrigger ManualTrigger) Trigger {
	typ := TriggerUnionTypeManualTrigger

	return Trigger{
		ManualTrigger: &manualTrigger,
		Type:          typ,
	}
}

func CreateTriggerAutomationTrigger(automationTrigger AutomationTrigger) Trigger {
	typ := TriggerUnionTypeAutomationTrigger

	return Trigger{
		AutomationTrigger: &automationTrigger,
		Type:              typ,
	}
}

func CreateTriggerJourneySubmissionTrigger(journeySubmissionTrigger JourneySubmissionTrigger) Trigger {
	typ := TriggerUnionTypeJourneySubmissionTrigger

	return Trigger{
		JourneySubmissionTrigger: &journeySubmissionTrigger,
		Type:                     typ,
	}
}

func CreateTriggerJourneyAutomationTrigger(journeyAutomationTrigger JourneyAutomationTrigger) Trigger {
	typ := TriggerUnionTypeJourneyAutomationTrigger

	return Trigger{
		JourneyAutomationTrigger: &journeyAutomationTrigger,
		Type:                     typ,
	}
}

func (u *Trigger) UnmarshalJSON(data []byte) error {

	var automationTrigger AutomationTrigger = AutomationTrigger{}
	if err := utils.UnmarshalJSON(data, &automationTrigger, "", true, nil); err == nil {
		u.AutomationTrigger = &automationTrigger
		u.Type = TriggerUnionTypeAutomationTrigger
		return nil
	}

	var journeySubmissionTrigger JourneySubmissionTrigger = JourneySubmissionTrigger{}
	if err := utils.UnmarshalJSON(data, &journeySubmissionTrigger, "", true, nil); err == nil {
		u.JourneySubmissionTrigger = &journeySubmissionTrigger
		u.Type = TriggerUnionTypeJourneySubmissionTrigger
		return nil
	}

	var manualTrigger ManualTrigger = ManualTrigger{}
	if err := utils.UnmarshalJSON(data, &manualTrigger, "", true, nil); err == nil {
		u.ManualTrigger = &manualTrigger
		u.Type = TriggerUnionTypeManualTrigger
		return nil
	}

	var journeyAutomationTrigger JourneyAutomationTrigger = JourneyAutomationTrigger{}
	if err := utils.UnmarshalJSON(data, &journeyAutomationTrigger, "", true, nil); err == nil {
		u.JourneyAutomationTrigger = &journeyAutomationTrigger
		u.Type = TriggerUnionTypeJourneyAutomationTrigger
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Trigger", string(data))
}

func (u Trigger) MarshalJSON() ([]byte, error) {
	if u.ManualTrigger != nil {
		return utils.MarshalJSON(u.ManualTrigger, "", true)
	}

	if u.AutomationTrigger != nil {
		return utils.MarshalJSON(u.AutomationTrigger, "", true)
	}

	if u.JourneySubmissionTrigger != nil {
		return utils.MarshalJSON(u.JourneySubmissionTrigger, "", true)
	}

	if u.JourneyAutomationTrigger != nil {
		return utils.MarshalJSON(u.JourneyAutomationTrigger, "", true)
	}

	return nil, errors.New("could not marshal union type Trigger: all fields are null")
}
