// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

// VariableAssignment - Represents a variable assignment with its expression and optional resolved value. Used for dynamic user assignments that get resolved during workflow execution.
type VariableAssignment struct {
	// The resolved values after variable evaluation (populated during execution)
	Value []string `json:"value,omitempty"`
	// The variable expression, e.g., "{{entity.owner}}"
	Variable string `json:"variable"`
}

func (v VariableAssignment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VariableAssignment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VariableAssignment) GetValue() []string {
	if v == nil {
		return nil
	}
	return v.Value
}

func (v *VariableAssignment) GetVariable() string {
	if v == nil {
		return ""
	}
	return v.Variable
}
