// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-workflow/internal/sdk/internal/utils"
)

type FlowType string

const (
	FlowTypeSection FlowType = "Section"
	FlowTypeStep    FlowType = "Step"
)

type Flow struct {
	Section *Section `queryParam:"inline" name:"flow"`
	Step    *Step    `queryParam:"inline" name:"flow"`

	Type FlowType
}

func CreateFlowSection(section Section) Flow {
	typ := FlowTypeSection

	return Flow{
		Section: &section,
		Type:    typ,
	}
}

func CreateFlowStep(step Step) Flow {
	typ := FlowTypeStep

	return Flow{
		Step: &step,
		Type: typ,
	}
}

func (u *Flow) UnmarshalJSON(data []byte) error {

	var section Section = Section{}
	if err := utils.UnmarshalJSON(data, &section, "", true, nil); err == nil {
		u.Section = &section
		u.Type = FlowTypeSection
		return nil
	}

	var step Step = Step{}
	if err := utils.UnmarshalJSON(data, &step, "", true, nil); err == nil {
		u.Step = &step
		u.Type = FlowTypeStep
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Flow", string(data))
}

func (u Flow) MarshalJSON() ([]byte, error) {
	if u.Section != nil {
		return utils.MarshalJSON(u.Section, "", true)
	}

	if u.Step != nil {
		return utils.MarshalJSON(u.Step, "", true)
	}

	return nil, errors.New("could not marshal union type Flow: all fields are null")
}

type WorkflowDefinition struct {
	AssignedTo     []string          `json:"assignedTo,omitempty"`
	ClosingReasons []ClosingReasonID `json:"closingReasons,omitempty"`
	// ISO String Date & Time
	CreationTime *string `json:"creationTime,omitempty"`
	Description  *string `json:"description,omitempty"`
	DueDate      *string `json:"dueDate,omitempty"`
	// set a Duedate for a step then a specific
	DynamicDueDate *DynamicDueDate `json:"dynamicDueDate,omitempty"`
	// Indicates whether this workflow is available for End Customer Portal or not. By default it's not.
	EnableECPWorkflow *bool   `json:"enableECPWorkflow,omitempty"`
	Flow              []Flow  `json:"flow"`
	ID                *string `json:"id,omitempty"`
	// ISO String Date & Time
	LastUpdateTime         *string                  `json:"lastUpdateTime,omitempty"`
	Name                   string                   `json:"name"`
	UpdateEntityAttributes []UpdateEntityAttributes `json:"updateEntityAttributes,omitempty"`
	// This field is deprecated. Please use assignedTo
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	UserIds []float64 `json:"userIds,omitempty"`
}

func (w *WorkflowDefinition) GetAssignedTo() []string {
	if w == nil {
		return nil
	}
	return w.AssignedTo
}

func (w *WorkflowDefinition) GetClosingReasons() []ClosingReasonID {
	if w == nil {
		return nil
	}
	return w.ClosingReasons
}

func (w *WorkflowDefinition) GetCreationTime() *string {
	if w == nil {
		return nil
	}
	return w.CreationTime
}

func (w *WorkflowDefinition) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *WorkflowDefinition) GetDueDate() *string {
	if w == nil {
		return nil
	}
	return w.DueDate
}

func (w *WorkflowDefinition) GetDynamicDueDate() *DynamicDueDate {
	if w == nil {
		return nil
	}
	return w.DynamicDueDate
}

func (w *WorkflowDefinition) GetEnableECPWorkflow() *bool {
	if w == nil {
		return nil
	}
	return w.EnableECPWorkflow
}

func (w *WorkflowDefinition) GetFlow() []Flow {
	if w == nil {
		return []Flow{}
	}
	return w.Flow
}

func (w *WorkflowDefinition) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *WorkflowDefinition) GetLastUpdateTime() *string {
	if w == nil {
		return nil
	}
	return w.LastUpdateTime
}

func (w *WorkflowDefinition) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WorkflowDefinition) GetUpdateEntityAttributes() []UpdateEntityAttributes {
	if w == nil {
		return nil
	}
	return w.UpdateEntityAttributes
}

func (w *WorkflowDefinition) GetUserIds() []float64 {
	if w == nil {
		return nil
	}
	return w.UserIds
}
