workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://docs.api.epilot.io/workflows-definition.yaml
targets:
    terraform:
        target: terraform
        source: my-source
