// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"
)

func (r *TaxResourceModel) ToCreateSDKType() *shared.TaxCreate {
	active := r.Active.ValueBool()
	description := r.Description.ValueString()
	rate := r.Rate.ValueString()
	region := shared.TaxCreateRegion(r.Region.ValueString())
	typeVar := shared.TaxCreateType(r.Type.ValueString())
	out := shared.TaxCreate{
		Active:      active,
		Description: description,
		Rate:        rate,
		Region:      region,
		Type:        typeVar,
	}
	return &out
}

func (r *TaxResourceModel) ToGetSDKType() *shared.TaxCreate {
	out := r.ToCreateSDKType()
	return out
}

func (r *TaxResourceModel) ToUpdateSDKType() *shared.TaxCreate {
	out := r.ToCreateSDKType()
	return out
}

func (r *TaxResourceModel) ToDeleteSDKType() *shared.TaxCreate {
	out := r.ToCreateSDKType()
	return out
}

func (r *TaxResourceModel) RefreshFromGetResponse(resp *shared.Tax) {
	r.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339Nano))
	if resp.ID != nil {
		r.ID = types.StringValue(*resp.ID)
	} else {
		r.ID = types.StringNull()
	}
	r.Org = types.StringValue(resp.Org)
	if len(r.Owners) > len(resp.Owners) {
		r.Owners = r.Owners[:len(resp.Owners)]
	}
	for ownersCount, ownersItem := range resp.Owners {
		var owners1 EntityOwner
		owners1.OrgID = types.StringValue(ownersItem.OrgID)
		if ownersItem.UserID != nil {
			owners1.UserID = types.StringValue(*ownersItem.UserID)
		} else {
			owners1.UserID = types.StringNull()
		}
		if ownersCount+1 > len(r.Owners) {
			r.Owners = append(r.Owners, owners1)
		} else {
			r.Owners[ownersCount].OrgID = owners1.OrgID
			r.Owners[ownersCount].UserID = owners1.UserID
		}
	}
	r.Schema = types.StringValue(resp.Schema)
	r.Tags = nil
	for _, v := range resp.Tags {
		r.Tags = append(r.Tags, types.StringValue(v))
	}
	r.Title = types.StringValue(resp.Title)
	r.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339Nano))
	r.Active = types.BoolValue(resp.Active)
	r.Description = types.StringValue(resp.Description)
	r.Rate = types.StringValue(resp.Rate)
	r.Region = types.StringValue(string(resp.Region))
	r.Type = types.StringValue(string(resp.Type))
}

func (r *TaxResourceModel) RefreshFromCreateResponse(resp *shared.Tax) {
	r.RefreshFromGetResponse(resp)
}

func (r *TaxResourceModel) RefreshFromUpdateResponse(resp *shared.Tax) {
	r.RefreshFromGetResponse(resp)
}
