// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AutomationInputContext struct {
	Source types.String `tfsdk:"source"`
	TaskID types.String `tfsdk:"task_id"`
}
