// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type DynamicDueDate struct {
	ActionTypeCondition types.String `tfsdk:"action_type_condition"`
	NumberOfUnits       types.Number `tfsdk:"number_of_units"`
	StepID              types.String `tfsdk:"step_id"`
	TimePeriod          types.String `tfsdk:"time_period"`
}
