// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ECPDetails struct {
	Description types.String `tfsdk:"description"`
	Enabled     types.Bool   `tfsdk:"enabled"`
	Journey     *StepJourney `tfsdk:"journey"`
	Label       types.String `tfsdk:"label"`
}
