// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ManualTrigger struct {
	EntitySchema types.String `tfsdk:"entity_schema"`
	ID           types.String `tfsdk:"id"`
	Type         types.String `tfsdk:"type"`
}
