// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Section struct {
	ID    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	Order types.Number `tfsdk:"order"`
	Steps []Step       `tfsdk:"steps"`
	Type  types.String `tfsdk:"type"`
}
