// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type StepJourney struct {
	ID        types.String `tfsdk:"id"`
	JourneyID types.String `tfsdk:"journey_id"`
	Name      types.String `tfsdk:"name"`
}
