// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Task struct {
	AutomationTask *AutomationTask `queryParam:"inline" tfsdk:"automation_task" tfPlanOnly:"true"`
	DecisionTask   *DecisionTask   `queryParam:"inline" tfsdk:"decision_task" tfPlanOnly:"true"`
	TaskBase       *TaskBase       `queryParam:"inline" tfsdk:"task_base" tfPlanOnly:"true"`
}
