// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Task struct {
	AutomationTask *AutomationTask `queryParam:"inline" tfsdk:"automation_task"`
	DecisionTask   *DecisionTask   `queryParam:"inline" tfsdk:"decision_task"`
	TaskBase       *TaskBase       `queryParam:"inline" tfsdk:"task_base"`
}
