// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Trigger struct {
	AutomationTrigger        *AutomationTrigger        `queryParam:"inline" tfsdk:"automation_trigger"`
	JourneyAutomationTrigger *JourneyAutomationTrigger `queryParam:"inline" tfsdk:"journey_automation_trigger"`
	JourneySubmissionTrigger *JourneySubmissionTrigger `queryParam:"inline" tfsdk:"journey_submission_trigger"`
	ManualTrigger            *JourneyAutomationTrigger `queryParam:"inline" tfsdk:"manual_trigger"`
}
