// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UpdateEntityAttributes struct {
	Source types.String `tfsdk:"source"`
	Target Target       `tfsdk:"target"`
}
