// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Value struct {
	Source types.String `tfsdk:"source"`
	Value  types.String `tfsdk:"value"`
}
